apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-app
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: core-app
  template:
    metadata:
      labels:
        app: core-app
    spec:
      containers:
      - image: ghcr.io/jorisla/core-app:main
        name: core-app
        ports:
        - containerPort: 8080